services:
  db:
    image: postgres
    networks:
      - backend
    env_file:
      - server/.env
    ports:
      - "5432:5432"
    volumes:
      - ${PWD}/server/postgres_init.sh:/docker-entrypoint-initdb.d/init.sh
      - pgdata:/var/lib/postgresql/data

  client:
    build:
      context: ${PWD}
      dockerfile: client/Dockerfile
    image: client
    environment:
      CHOKIDAR_USEPOLLING: true
    stdin_open: true
    networks:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ${PWD}/client:/app/client
    command: npm start
    depends_on:
      - server

  server:
    build:
      context: ${PWD}
      dockerfile: server/Dockerfile
    image: server
    networks:
      - backend
    ports:
      - "3001:3001"
    volumes:
      - ${PWD}/server:/app/server
    command: npm run dev
    depends_on:
      - db
networks:
  backend: {}

volumes:
  pgdata: {}
